version: '3'
services:
  mysql_compose:
    image: mysql:5.7
    container_name: mysql_compose
    restart: always
    ports:
      - 3366:3306
    volumes:
      - /env/mysql/data:/var/lib/mysql
      - /env/mysql/conf/mymysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "MyP@55wd"
